[metadata]
name = lexmechanicus-server
version = 0.1.0

[options]
packages = find:
install_requires =
    fastapi
    uvicorn[standard]
    SQLAlchemy[asyncio]
    asyncpg
    pgvector
    redis
    aioboto3
    python-multipart
    pydantic
    orjson
    sse-starlette
    httpx
    bcrypt
    pyjwt
    alembic
    pypdf
    markdown-it-py
package_dir =
    = .

[options.packages.find]
include =
    app
exclude =
    alembic
